--- 
:rtmpd_server: localhost
:rtmpd_port: 2342
:uce_server: localhost
:uce_port: 5280
:uce_method: http
:uce_prefix: /api/0.5
:uce_uid: encre-video
:uce_token: "123456"
:logfile: STDOUT
:loglevel: DEBUG
:token_secret: givemeagoodrandomsecret
:tokensecret: testtoken
